### ISSUE TITLE
Support 409 conflict for post requests

### ISSUE THREAD

**Issue by ordnungswidrig** [clojure-liberator/liberator#107]
While RFC2626 suggests only PUT requests to return 409, this can also be useful for POST requests.

See https://groups.google.com/forum/#!topic/clojure-liberator/RmR1RzIxBh0

**Comment by sethkrasnianski** [comment]
+1

**Comment by ordnungswidrig** [comment]
I'm open for a PR. I suggest to support conflict for POST to move the decision "conflict?" be before "post-to-existing?" (see the graph for reference: http://clojure-liberator.github.io/liberator/assets/img/decision-graph.svg). After that change `conflict?` will be called for POST and PUT requests.
