### ISSUE TITLE
Is it possible to know the route of each request in the flowchart?

### ISSUE THREAD

**Issue by plucury** [clojure-liberator/liberator#17]
I think it would very useful for debugging.

**Comment by bostonaholic** [comment]
Any updates on this?

**Comment by ordnungswidrig** [comment]
This has been implemented since quite a while. See [debugging documentation](http://clojure-liberator.github.io/liberator/doc/debugging.html) for reference.

TLDR:

```clojure
(def handler
  (-> app
      (wrap-trace :header :ui)))
```

and have it at `/x-liberator/requests`.
