### ISSUE TITLE
Way to set global response?

### ISSUE THREAD

**Issue by Rugal** [clojure-liberator/liberator#193]
Hi all:
    I find Liberator very interesting and useful. Now I am trying to do some small stuff based on it.  
    Sometimes I need a global response to form a unified thing to handle whenever request method is not allowed or some media types are not supported, so I do not need to specify them for every suitable situations one by one.
    Is there anything similar like that in Liberator?

**Comment by Rugal** [comment]
In google group Fairuz mentioned he achieve it by something like this:

    (def return {:ok {:responseType "SUCCESS" :code "20001" :message "Information provided"}
             :created {:responseType "SUCCESS" :code "20101" :message "Information saved"}
             :no-result {:responseType "SUCCESS" :code "20401" :message "No result"}
             :missing-information {:responseType "ERROR" :code "40002" :message "Mandatory information missing"}
             :missing-command {:responseType "ERROR" :code "40002" :message "Missing command"}
             :token-invalid {:responseType "ERROR" :code "40302" :message "Token not valid"}
             :token-expired {:responseType "ERROR" :code "40303" :message "Token expired"}
             :server-error {:responseType "ERROR" :code "50001" :message "Internal server error"}
             :database-error {:responseType "ERROR" :code "50002" :message "Database error"}
             :process-error {:responseType "ERROR" :code "50003" :message "Unprocessable entity"}})

But in this case you still need to specify those responses for each resource one by one.  
What I think the best is like in springmvc, one could do like [this](https://github.com/Rugal/springmvc-spring-hibernate/blob/master/src/main/resources/archetype-resources/src/main/java/rugal/sample/controller/ExceptionAction.java#L105), which is so convenient since you just set it once and any situation matched will throw exception to respond exactly the same thing.   
I feel this is so good and I am searching for this in liberator.

**Comment by ordnungswidrig** [comment]
You can define a map of defaults to be used for multiple resource definitions. This is described in the [documentation](http://clojure-liberator.github.io/liberator/doc/resource-definition.html#base-implementation-span-classlabel-label-infosince-0110spann). When you want to return similar response for different handles  then nothing keeps you from defining a helper function:

`(defn api-response [type code message]
  {:responseType type :code code :message message})

(def handler-defaults {
  :handle-ok (api-response :success 20001 "Information provided")
  :handle-created (api-response :success 20101 "Information saved")
  #...
})

(defresource foo []
  handler-defaults 
  :exists? false)

(defresource bar []
  handler-defaults 
  :allowed-methods [])
`

The two example resources will have all the handler definitions defined in handler-defaults. Note that this works for every declaration of a resource not only handlers.
