### ISSUE TITLE
Header "Location" not set for 303 [Was: 303 with body set?]

### ISSUE THREAD

**Issue by timvisher** [clojure-liberator/liberator#212]
According to [httpstatus.es](http://httpstatus.es/303), `303` bodies should contain a link to the resource. I can't seem to find a way to do that in liberator. Am I missing something in the docs?

**Comment by timvisher** [comment]
Actually, I can define `:handle-see-other` and my body is set _and_ my status is set to `303`, but my `Location` header goes away.

```
> ((liberator/resource
                                                                    :allowed-methods [:post :get]
                                                                    :post-redirect? {:location "//localhost/"})
                                                                   (r/request :post "/"))
{:headers {"Location" "//localhost/"}, :status 303}
> ((liberator/resource
                                                                    :allowed-methods [:post :get]
                                                                    :post-redirect? {:location "//localhost/"}
                                                                    :handle-see-other "ohai")
                                                                   (r/request :post "/"))
{:headers {"Content-Type" "text/plain;charset=UTF-8"}, :body "ohai", :status 303}
```

**Comment by timvisher** [comment]
My reading of http://clojure-liberator.github.io/liberator/doc/handlers.html indicates that `"Location"` should be set in the `:headers` of that response given that it has `:location` in the ctx.

**Comment by ordnungswidrig** [comment]
Hi Tim!

This is actually a bug, liberator creates the "location" header only for status 201. Unfortunately the midje test had a bug, too and did not catch this. I'm working in a patch.

**Comment by timvisher** [comment]
So this signals my firsts semi-meaningful contribution to liberator! \\( ﾟ◡ﾟ)/

**Comment by ordnungswidrig** [comment]
I hope @timvisher there will be more! :-)
