### ISSUE TITLE
A Conflict? still triggers put! on the resource

### ISSUE THREAD

**Issue by johnboy14** [clojure-liberator/liberator#228]
I'm not sure if this is an issue or if I am using Liberator incorrectly.  I want to return a 409 when the client tries to add a user that already exists, to achieve this I am using the Conflict? decision.  When :conflict? returns true my :put! method is still be executed, which I think is undesired behaviour.  I consulted the decision graph and in the event of a conflict? it does not talk about executing my put! but immediately returns a 409.  As a work around I have to handle the conflict and use a conditional switch on my put! action.

`(defresource create [payload]`
` :allowed-methods [:put]`
` :available-media-types ["application/json"]`
` :conflict? (service/user-exist? (retrieve-params payload))`
` :put! (service/create-user (retrieve-params payload))))`
 `:handle-created :record)`

**Comment by ordnungswidrig** [comment]
Your declarations at `conflict?` and `put!` are executed at resource definition time and end up in the resource definition map as constant values. I think you want something like this:

```clojure
(defresource create [payload]
:allowed-methods [:put]
:available-media-types ["application/json"]
:conflict? (fn [ctx] (service/user-exist? (retrieve-params payload)))
:put! (fn [ctx] (service/create-user (retrieve-params payload)))))
:handle-created :record)
```

**Comment by johnboy14** [comment]
Yeah this works.  Cheers.  Sorry for putting this in the issues page.  Is there somewhere more appropriate to ask these kind of questions?.

**Comment by ordnungswidrig** [comment]
There's a google group https://groups.google.com/forum/#!forum/clojure-liberator or the clojurians slack room at https://clojurians.slack.com/messages/liberator/
