### ISSUE TITLE
Swagger support for Liberator

### ISSUE THREAD

**Issue by timur87** [clojure-liberator/liberator#237]
Hi,

Are you planning to support swagger? It's going to be some sort of standard. Out of box support would be great and would increase the chance of adoption for liberator, in my opinion.

http://www.marketwired.com/press-release/new-collaborative-project-extend-swagger-specification-building-connected-applications-2070645.htm

**Comment by ordnungswidrig** [comment]
I, personally, am not a big fan of swagger which I consider too RPC orientated compared to the core idea of HTTP serving representational state transfer (REST). However, swagger is deployed successfully in all areas.

Swagger support will not be implemented in liberator anytime soon. But I can imagine a supporting library that allow to publish liberator resources to swagger. If you want to start such a project I will help where I can.

**Comment by simax** [comment]
I'm enjoying using liberator, thank you for giving it to the world :) But documentation for the api I've built has been on my mind for a while. As a matter of interest, what do you recommend? What do you use?

**Comment by danielmihai** [comment]
Hi @ordnungswidrig ,

What are we going to use for documenting the API and have at least a minimal interface to test our APIs ?

Keep up the great work! 

Thanks,
Daniel.

**Comment by ordnungswidrig** [comment]
Hi @danielmihai,

I tend to document the media-types used for the resource representation and the relations between resources. This is closer to a hypermedia approach and leads to decoupling of the actual resource deployment and the client implementation. In other words, teach the client to understand e.g. the relation `delete` and a media type that supports hyperlinks with relations and the client will be able to understand such link independent of the URI location.

**Comment by danielmihai** [comment]
Hi @ordnungswidrig,

Thank you for the timely response, do you have an example ? I only used swagger for documenting APIs and I will like to know other ways of doing API documentation.

Thanks!
