### ISSUE TITLE
defresource is broken when a docstring is provided

### ISSUE THREAD

**Issue by ordnungswidrig** [clojure-liberator/liberator#243]
`(defresource "docstring" defaults key1 arg1 key2 arg2)` is broken while
`(defresource defaults key1 arg1 key2 arg2 ...)` works as expected

**Comment by jjhop** [comment]
It looks like it is still not fixed. The problem looks uncomplicated. I will try to fix it with my next PR. Should I commit to the master or do a separate branch for it? @ordnungswidrig

**Comment by ordnungswidrig** [comment]
Please use a branch so we can have a quick PR review.
