### ISSUE TITLE
How to set additional headers?

### ISSUE THREAD

**Issue by punit-naik** [clojure-liberator/liberator#248]
The :available-media-types key inside a resource sets the "Content-Type" header. I wanted to know if there were options for setting more headers like "Content-Disposition" and also "Content-Length".

Please help!

**Comment by ordnungswidrig** [comment]
Have a look at the docs on how to alter the ring response created by liberator: http://clojure-liberator.github.io/liberator/doc/representations.html#altering-a-generated-response-span-classlabel-label-infosince-013span

Liberator only creates some headers itself, which are e.g. all things regarding content-negotiation and conditional requests.
