### ISSUE TITLE
add default headers on response

### ISSUE THREAD

**Issue by atstp** [clojure-liberator/liberator#249]
Is there a way to apply generic or default headers to responses? A lot of the endpoints I'm working with need ACAO headers set, and it's fairly tedious to use `ring-response` in each `handle-something` handler. 

I've checked out issue #74, what looks like [the relevant doc pages](http://clojure-liberator.github.io/liberator/doc/representations.html#altering-a-generated-response-span-classlabel-label-infosince-013span), and  [the defaults](http://clojure-liberator.github.io/liberator/doc/resource-definition.html#base-implementation-span-classlabel-label-infosince-0110span) &mdash; I'm pretty sure I'm not missing anything.

If there's not an existing approach, would it be possible to add some sort of `access-allowed` value and matching decision points?  If that (or some alternative) seems like a likely merge candidate, I'd be open to starting the work myself.

**Comment by ordnungswidrig** [comment]
Liberator resources are standard ring handlers and can be wrapped with ring middleware. As an alternative you can declare your own `:as-response` function which can delegate to liberator's implementation and add the necessary headers afterwards.

**Comment by atstp** [comment]
ah, that sounds great, thanks!
