### ISSUE TITLE
Extra span on documentation page

### ISSUE THREAD

**Issue by ssaul** [clojure-liberator/liberator#257]
Hello.

There is an extra span after the decision tree on the following page:
http://clojure-liberator.github.io/liberator/tutorial/decision-graph.html

**Comment by ordnungswidrig** [comment]
Thanks for the heads-up. There this seem to be some recent change to github pages, there hasn't been any change recently to the markdown source. The same issue occurs on http://clojure-liberator.github.io/liberator/doc/decisions.html

**Comment by ordnungswidrig** [comment]
fixed by 21f6cd8

**Comment by ssaul** [comment]
Yeah, I saw that one too.  I figured they were connected some way, so if you fixed it one place it would be fixed in the other.  Thanks!
