### ISSUE TITLE
Post Does Not Return 200 OK

### ISSUE THREAD

**Issue by ertugrulcetin** [clojure-liberator/liberator#259]
I want my POST resource to return **200** OK so I can use :**handle-ok** but resource returns 201 Created.
I use my resource for the login operation.

**:handle-ok** does not run !!!!
Here is the code: 

```
(POST "/login" []
             (resource :allowed-methods [:post]
                       :available-media-types resource-util/avaliable-media-types
                       :known-content-type? #(resource-util/check-content-type % resource-util/avaliable-media-types)
                       :malformed? #(resource-util/parse-json % ::data)
                       :post! (fn [ctx]
                                {:my-data "oki"})
                       :handle-ok (fn [ctx]
                                    {:ok? true})))
```

**Comment by ordnungswidrig** [comment]
You need to return false from `new?` and true from `respond-with-entity?` to make POST return 200.

This is the reference for the decisions: http://clojure-liberator.github.io/liberator/doc/decisions.html 
The decision graph can be helpful to see which path is taken.

**Comment by ertugrulcetin** [comment]
Thank you!
