### ISSUE TITLE
Gray out the Internal decision points in the graph

### ISSUE THREAD

**Issue by vspinu** [clojure-liberator/liberator#262]
I am constantly eyeballing the graph trying to familiarize myself with the system. Unfortunately the internal decision nodes are quite an annoyance. Would it be possible to gray them out in the graph?  

It's probably a simple change if you already track which nodes are internal and which are not.

Thanks.

**Comment by ordnungswidrig** [comment]
This is a good proposal which I have done in a local branch while refactoring the content negotiation decisions.

**Comment by ordnungswidrig** [comment]
This is implemented as part of #229, closing this ticket.
