### ISSUE TITLE
How to redirect get methods also other methods?

### ISSUE THREAD

**Issue by ertugrulcetin** [clojure-liberator/liberator#277]
I have an endpoint called `/account ` which provides user info(returns html).

When unauthorised user tries to access this endpoint I need to be able to redirect to `login page` but in Liberator I found `post-redirect `so far and it is just for `post methods`.

I need to redirect `get methods` as well, how can I achieve this?

**Comment by ordnungswidrig** [comment]
You can implement `moved-temporarily?` do force a redirection, return the location target in context:

```clojure
(resource
  ...
  :moved-temporarily? (fn [ctx] {:location "/somewhere"}))
```

In my opinion a better way to implement this is to use `:authorized?` and return the login page from `:handle-unauthorized`. However constraints on your architecture might make a redirection preferrable.

**Comment by ertugrulcetin** [comment]
Thank you so much!
