### ISSUE TITLE
Show the default path in the flowchart

### ISSUE THREAD

**Issue by bostonaholic** [clojure-liberator/liberator#285]
I often times use the flowchart to determine which decisions and handlers I need for a particular resource and method. Often times, it's unclear which of the `true`/`false` path is the default path. It'd be nice if the flowchart made this clear.

**Comment by ordnungswidrig** [comment]
This is an interesting idea. The problem though is that there is no simple answer which is the default. Any declaration takes a function and thus the result cannot be detected at compile time. There might be a ways to detect constant declaration in the defaults but I don't see a simple way how incorporate that into the graph.
