### ISSUE TITLE
Documentation (Decision Graph) broken

### ISSUE THREAD

**Issue by beoliver** [clojure-liberator/liberator#288]
All links to [http://clojure-liberator.github.io/liberator/assets/img/decision-graph.svg](http://clojure-liberator.github.io/liberator/assets/img/decision-graph.svg) return the following:

> This page contains the following errors:
> error on line 3 at column 6: XML declaration allowed only at the start of the document
> Below is a rendering of the page up to the first error.

As far as I am aware there is cuurently nowhere on the web to actually view the graph?

**Comment by ordnungswidrig** [comment]
Fixed! Thanks!
