### ISSUE TITLE
Reliance on  javax.xml.ws

### ISSUE THREAD

**Issue by danielsz** [clojure-liberator/liberator#290]
Users that are upgrading the JDK to the latest version (9) will not be able to run liberator applications  without some modifications in their build tools. This is due to the new module system in java 9. 
For example, Boot users  will have to do something like this in the shell:
```shell
export BOOT_JVM_OPTIONS='--add-modules=java.xml.ws'   
```
Not the end of the world, but annoying at this time of transition when some environments are still using one version and others the new one. 

Now, I am not familiar with `liberator`'s code base, but it seems that the only call that warrants the JAX-WS APIs is `ProtocolException` and if that could be made redundant, it would be a boon for everybody.

Thank you for considering this avenue of action.

**Comment by ordnungswidrig** [comment]
Thanks for the heads-up. The fix should be easy.

**Comment by brogowski** [comment]
It looks like a good issue to start with.

Any recommendations how it should be replaced?
Like: swapping with RuntimeException, using ex-info or creating new ProtocolException class?

**Comment by ordnungswidrig** [comment]
@brogowski yes, ex-info is fine. You can match on a keyword in the catch clause roughtly like we match on the `ProtocolException` class currently.

**Comment by MikaelSmith** [comment]
Any chance we'll see a release of this soon?

**Comment by ordnungswidrig** [comment]
@mikaelSmith I totally forgot about that. Will release as soon as I find the time, ~this week.

**Comment by ordnungswidrig** [comment]
0.15.2 was released today.
