### ISSUE TITLE
`combine` results in a lazy seq for lists and vectors

### ISSUE THREAD

**Issue by DaoWen** [clojure-liberator/liberator#293]
Liberator's [`combine`](https://github.com/clojure-liberator/liberator/blob/0.15.1/src/liberator/util.clj#L57-L74) utility function is supposed to do an intelligent merge on certain types of data. E.g., for sets and maps:

```clojure
   (and (map? curr) (map? newval)) (merge-with combine curr newval)
   (and (set? curr) (coll? newval)) (set (concat curr newval))
```

Compare that with what happens with lists and vectors:

```clojure
   (and (list? curr) (coll? newval)) (concat curr newval)
   (and (vector? curr) (coll? newval)) (concat curr newval)
```
https://github.com/clojure-liberator/liberator/blob/0.15.1/src/liberator/util.clj#L79-L80

Since `concat` returns a lazy sequence, if you have two successive updates to a list or vector value, the second update will see a lazy seq rather than the original list/vector type. Think about this example:

1. First decision adds an entry `::foo [1]` to the context
2. Second decision updates the context with `::foo [2]`, resulting in `::foo (1 2)`
3. Third decision updates the context with `::foo [3]`, resulting in `::foo [3]`.

Based on the documentation, I would have expected the successive values `[1]` then `[1 2]` then `[1 2 3]` to be stored in the context with the key `::foo`—but that's not what happens.

I recommend using `into` rather than `concat` to solve this. If the user wants to do something more efficient (e.g., using `concat`), then they can always manually build the new value and pass it in meta-tagged with `^:replace`.

**Comment by ordnungswidrig** [comment]
Patch welcome. Using `into` seems the way to go.
