### ISSUE TITLE
Blocking upgrade to java 9 & 10

### ISSUE THREAD

**Issue by austb** [clojure-liberator/liberator#298]
The unreleased change from [this commit](https://github.com/clojure-liberator/liberator/commit/281e0a9173ea45186788ce8e0c68ce056475078c) is blocking our upgrade off of java 8.

Can you release a new version?

**Comment by austb** [comment]
The following options allow it to run in Java 8, 9, and 10. But the deprecated modules will be removed entirely in Java 11, so a release is still needed.

```
:jvm-opts ["-XX:+IgnoreUnrecognizedVMOptions"
           "--add-modules=java.xml.bind"
           "--add-modules=java.xml.ws"]
```

**Comment by ordnungswidrig** [comment]
0.15.2 was released today and drops the dependency to `java.xml.ws`

**Comment by austb** [comment]
Thanks!
