### ISSUE TITLE
javax.xml.ws on java 11

### ISSUE THREAD

**Issue by trevor** [clojure-liberator/liberator#301]
This fix related to `javax.xml.ws` no longer works on Java 11:

https://github.com/clojure-liberator/liberator/issues/290

Error given:
`Caused by: java.lang.ClassNotFoundException: javax.xml.ws.ProtocolException`

The module was removed in Java 11.

**Comment by yayitswei** [comment]
I'm also seeing this issue doing regression testing on Liberator 0.12.2.

**Comment by ordnungswidrig** [comment]
The dependency on `javax.xml.ws` was dropped in #291 and release in `0.15.2`.
