### ISSUE TITLE
A new home for the examples?

### ISSUE THREAD

**Issue by jeremyheiler** [clojure-liberator/liberator#306]
Since I removed the examples in #303, I moved them into a separate repository. I kept the git commit history from the `examples/` directory, added `liberator` to the namespaces, and moved the example tests over.

https://github.com/jeremyheiler/liberator-examples

Would you like to import this repository into this org?

**Comment by ordnungswidrig** [comment]
Good idea! Also at some point these should be enhanced. The clojurescript is a little ancient :)
