### ISSUE TITLE
duplicate 501 response

### ISSUE THREAD

**Issue by boxxxie** [clojure-liberator/liberator#31]
```clojure
(defhandler handle-unknown-method 501 "Unknown method.")
```

```clojure
(defhandler handle-not-implemented 501 "Not implemented.")
```

http://en.wikipedia.org/wiki/List_of_HTTP_status_codes
>405 Method Not Allowed
A request was made of a resource using a request method not supported by that resource;[2] for example, using GET on a form which requires data to be presented via POST, or using PUT on a read-only resource.

maybe the below should be switched to  
```clojure
(defhandler handle-unknown-method 405 "Method Not Allowed.")
```

**Comment by ordnungswidrig** [comment]
This is covered by #120
