### ISSUE TITLE
multiple-representations? emits 310 instead of 300

### ISSUE THREAD

**Issue by ataggart** [clojure-liberator/liberator#42]
If I understand the usage correctly, this decision corresponds to [300 Multiple Choices](http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.3.1).

I noticed it when reading the [decisions docs](http://clojure-liberator.github.io/liberator/doc/decisions.html), and confirmed it in [the source](https://github.com/clojure-liberator/liberator/blob/master/src/liberator/core.clj#L226).

**Comment by vidraj** [comment]
This was fixed in the code and in the decision graph, but not in the list of decision points at <https://clojure-liberator.github.io/liberator/doc/decisions.html>, which still says
> Should the response be 310 multiple representations?
