### ISSUE TITLE
Merging the return value of a decision causes duplicate values in vectors

### ISSUE THREAD

**Issue by ebaxt** [clojure-liberator/liberator#60]
``` clojure
:allowed-methods [:put :delete :get]
  :available-media-types ["application/json"]
  :allowed? (fn [_]
                     {::instance {:children ["one" "two"]})
  :exists? ::instance
  :can-put-to-missing? false
  :new? false
  :respond-with-entity? (fn [{{method :request-method} :request}] (= :put method))
  :put! (fn [ctx]
          (let [old (get ctx ::instance)
                new {::instance {:children ["one"]}]))
...
  :handle-ok (fn [ctx]
               (get ctx ::instance)))
```

The above example yields ["one" "one" "two"], but I think it's reasonable to expect the same behavior  as merge?

``` clojure
user=> (merge {:foo ["one" "two"]} {:foo ["one"]})
{:foo ["one"]}
```

Caused by the use of concat on lists and vectors: 
https://github.com/clojure-liberator/liberator/blob/master/src/liberator/core.clj#L77

Mail group thread:

http://groups.google.com/group/clojure-liberator/t/4c58338847eb585e

**Comment by bago2k4** [comment]
👍 
We are hitting this bug in production and it's pretty annoying, have you found a solution... yet?

**Comment by ordnungswidrig** [comment]
This is a know regression in the way `combine` works. `liberator.util/combine` works like a recursive merge but id will also concat lists, vectory and sets.

You can attach the meta data attribute `:replace` to prevent a merge:

```clojure
user=> (combine {:foo [:bar :baz]} {:foo ^:replace [:qux]})
{:foo [:qux]}
```

**Comment by bago2k4** [comment]
We had a similar issue caused by this "deep merge/concat" algorithm, we solved it using `^:replace`.
For those who wonder you can't use `with-meta` with all values but you can add it conditionally:

```
(defn rep [v]
  (if (instance? clojure.lang.IMeta v)
    (with-meta v {:replace true})
    v))
```
