### ISSUE TITLE
:handle-created change/add headers

### ISSUE THREAD

**Issue by yatesj9** [clojure-liberator/liberator#76]
Am i able to change or add headers to :handle-created??

I need to to add 
"Access-Control-Allow-Origin", "*"
"Access-Control-Allow-Headers", "X-Requested-With"
"Access-Control-Allow-Methods", "GET, POST","PUT"

I've tried in the resource to simply specify a MAP, but all it does is automatically add it to the body

**Comment by Rugal** [comment]
This functionality is useful when I want to build a Angular client webservice, please release this version. I am looking forward the version that include this feature.

**Comment by wqhhust** [comment]
Is http-representation still available? I can't find it from https://github.com/clojure-liberator/liberator/commits/master/src/liberator/representation.clj.

**Comment by wqhhust** [comment]
please release this version, it's useful.

**Comment by ordnungswidrig** [comment]
@wqhhust with current liberator 0.13 you can use `as-response` to do that for you. See [docs on altering a representation](http://clojure-liberator.github.io/liberator/doc/representations.html#altering-a-generated-response-span-classlabel-label-infosince-013span)

```clojure
(defresource x
  :available-media-types ["application/json"]
  :handle-ok (fn [ctx] (ring-response
                         {:some "json"}
                         {:headers {"X-Foo-Header" "This is liberator"}})))
;; This creates the same response as without ring-response but additionally
;; sets the header "X-Foo-Header"
```

**Comment by wqhhust** [comment]
@ordnungswidrig 

Your solutions works for get method, But won't work for post method. I coded the following, with the same solutions for both get and post. But if I call the post, it still throw the error of 
    
XMLHttpRequest cannot load http://localhost:6003/alert/1. No 'Access-Control-Allow-Origin' header is present on the requested resource. 


    (defresource alert [id]
    ;  (secured-resource {:allowed? (by-method {:get true :delete #(any-granted? % [:catalog-admin]) :put #(any-granted? % [:catalog-admin])})})
      :available-media-types ["application/json"]
      :allowed-methods       [:get :put :post :options]
      :post! (fn[ctx]
               (println "in side post!.........")
               (println "********* post")
               (ring-response {:some "json from post"}
                              {:headers {"Access-Control-Allow-Origin" "*"}})
               )
      :handle-ok             (fn [ctx]
                               (println "********* get")
                               (ring-response {:some "json from get"}
                                              {:headers {"Access-Control-Allow-Origin" "*"}})
                               ))

**Comment by ordnungswidrig** [comment]
The actions like `post!` or `delete!` are not handlers and must not return a representation / response. Depending on how `post-redirect?`, `new?` and the other decisions evaluate different handlers are called. With the default settings, a POST request will end up at `handle-created`. See the [documentation on decisions](http://clojure-liberator.github.io/liberator/doc/decisions.html) for the default values.

This the the relevant part of the decision graph.

![image](https://cloud.githubusercontent.com/assets/24977/9577188/e1f95a00-4fde-11e5-81e3-7925eaf25f0c.png)

With a post request you can also end up and handle-ok, if `new?` returns false. If you want to return different representations in that case you would need to test on the request-method in the handler function.

**Comment by wqhhust** [comment]
@ordnungswidrig   Thank very much for your nice reply.

Original I didn't return representation/response in post! as following code, and both post/get  throws the error of No 'Access-Control-Allow-Origin',  then I used your following solution of for get, it fix the 
issue, but post still error with No 'Access-Control- hAllow-Origin'. So I copy the same solution to post! with the hope to fix the error, but it still error out.

    (fn [ctx] 
    (ring-response
    {:some "json"}
    {:headers {"X-Foo-Header" "This is liberator"}})))

I am using figwheel to dev SPA, and it needs to post to liberator data. Since figwheel and liberate works on different port on localhost, it throw No 'Access-Control-Allow-Origin' by default when access liberate POST method from figwheel clojurescript.  Although I fix it for GET using your solution. Post still doesn't work.

**Comment by ordnungswidrig** [comment]
In your case you should add the ring-response in handle-created too: 

```clojure
(defresource
  :allowed-methods [:get :post]
  :handle-ok ...
  :handle-created (fn [] (ring-response {:created-some "json" :headers {"X-Foo" "Liberator"}})))
```

What status code does your resource return on post? It should be 201.

As an alternative you can use some ring middleware around the resource or your routes.

**Comment by wqhhust** [comment]
I looked up the document and get its trace in UI (it's fantastic to easily trace!!!)
I use POST (cljx-ajax) in clojurescript, but the trace got is OPTIONS. 
howevery access-control-request-method tell us it's POST


Liberator Request Trace #b2422 at Tue Sep 01 06:54:53 CST 2015 (159s ago)

Request was ":OPTIONS /alert/2"

Parameters

Headers

origin
http://localhost:3449
host
localhost:6003
user-agent
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.114 Safari/537.36
access-control-request-headers
accept, content-type
referer
http://localhost:3449/
connection
keep-alive
accept
*/*
accept-language
en-US,en;q=0.8,zh-CN;q=0.6,zh;q=0.4
access-control-request-method
POST
accept-encoding
gzip,deflate,sdch
Trace

decision: service-available? true
decision: known-method? :options
decision: uri-too-long? false
decision: method-allowed? :options
decision: malformed? false
decision: authorized? true
decision: allowed? true
decision: valid-content-header? true
decision: known-content-type? true
decision: valid-entity-length? true
decision: is-options? true
handler: handle-options nil

**Comment by wqhhust** [comment]
In this link
http://stackoverflow.com/questions/1099787/jquery-ajax-post-sending-options-as-request-method-in-firefox

it said 
>  After this my cross domain requests from Firefox started working. As said before, the browser first sends the OPTIONS request and then immediately after that the POST/GET

So I  put the following

    :handle-options (fn
       [ctx]
                    (println "********* option")
                    )

then trace it and the trace is the same as before, stopped at   handler: handle-options nil. But handle-options  actually got executed, since in the console I could see the following printed.
 "********* option

If I add some ring-response to handle-option as below

    :handle-options (fn
       [ctx]
                    (println "********* option")
                    (ring-response {:some "json from get"}
                                   {:headers {"Access-Control-Allow-Origin" "*" "Access-Control-Allow-Headers" "Content-Type"}})

Then it throws the error of 

********* option
java.lang.IllegalArgumentException: No method in multimethod 'render-map-generic' for dispatch value: null
              MultiFn.java:160 clojure.lang.MultiFn.getFn
              MultiFn.java:231 clojure.lang.MultiFn.invoke
        representation.clj:202 liberator.representation/eval6748[fn]
         representation.clj:15 liberator.representation/eval6484[fn]
        representation.clj:234 liberator.representation/liberator.representation.RingResponse
         representation.clj:15 liberator.representation/eval6484[fn]
         representation.clj:15 liberator.representation/eval6484[fn]
                  core.clj:179 liberator.core/run-handler
                  core.clj:462 liberator.core/handle-options
                   core.clj:85 liberator.core/decide
                  core.clj:464 liberator.core/is-options?
                   core.clj:85 liberator.core/decide
                  core.clj:467 liberator.core/valid-entity-length?
                   core.clj:85 liberator.core/decide
                  core.clj:470 liberator.core/known-content-type?
                   core.clj:85 liberator.core/decide
                  core.clj:472 liberator.core/valid-content-header?
                   core.clj:85 liberator.core/decide
                  core.clj:475 liberator.core/allowed?
                   core.clj:85 liberator.core/decide
                  core.clj:478 liberator.core/authorized?
                   core.clj:85 liberator.core/decide
                  core.clj:481 liberator.core/malformed?
                   core.clj:85 liberator.core/decide
                  core.clj:484 liberator.core/method-allowed?
                   core.clj:85 liberator.core/decide
                  core.clj:487 liberator.core/uri-too-long?
                   core.clj:85 liberator.core/decide
                  core.clj:490 liberator.core/known-method?
                   core.clj:85 liberator.core/decide
                  core.clj:493 liberator.core/service-available?
                  core.clj:580 liberator.core/run-resource
              resources.clj:39 acme-catalog.resources/alert[fn]
               response.clj:34 compojure.response/eval1471[fn]
                response.clj:7 compojure.response/eval1430[fn]
                  core.clj:113 compojure.core/make-route[fn]
                  core.clj:103 compojure.core/wrap-route-middleware[fn]
                   core.clj:41 compojure.core/if-route[fn]
                   core.clj:27 compojure.core/if-method[fn]
                  core.clj:127 compojure.core/routing[fn]
                 core.clj:2515 clojure.core/some
                  core.clj:127 compojure.core/routing
               RestFn.java:139 clojure.lang.RestFn.applyTo
                  core.clj:626 clojure.core/apply
                  core.clj:132 compojure.core/routes[fn]
                   dev.clj:229 liberator.dev/wrap-trace[fn]
                   dev.clj:197 liberator.dev/wrap-trace-ui[fn]
                  core.clj:127 compojure.core/routing[fn]
                 core.clj:2515 clojure.core/some
                  core.clj:127 compojure.core/routing
               RestFn.java:139 clojure.lang.RestFn.applyTo
                  core.clj:626 clojure.core/apply
                  core.clj:132 compojure.core/routes[fn]
                   dev.clj:206 liberator.dev/wrap-trace-header[fn]
             middleware.clj:36 buddy.auth.middleware/wrap-authentication[fn]
         keyword_params.clj:35 ring.middleware.keyword-params/wrap-keyword-params[fn]
                   json.clj:56 ring.middleware.json/wrap-json-params[fn]
                  Var.java:379 clojure.lang.Var.invoke
                 reload.clj:22 ring.middleware.reload/wrap-reload[fn]
             stacktrace.clj:23 ring.middleware.stacktrace/wrap-stacktrace-log[fn]
             stacktrace.clj:86 ring.middleware.stacktrace/wrap-stacktrace-web[fn]
                  jetty.clj:20 ring.adapter.jetty/proxy-handler[fn]
              (Unknown Source) ring.adapter.jetty.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle
       HandlerWrapper.java:116 org.eclipse.jetty.server.handler.HandlerWrapper.handle
               Server.java:369 org.eclipse.jetty.server.Server.handle
AbstractHttpConnection.java:486 org.eclipse.jetty.server.AbstractHttpConnection.handleRequest
AbstractHttpConnection.java:933 org.eclipse.jetty.server.AbstractHttpConnection.headerComplete
AbstractHttpConnection.java:995 org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete
           HttpParser.java:644 org.eclipse.jetty.http.HttpParser.parseNext
           HttpParser.java:235 org.eclipse.jetty.http.HttpParser.parseAvailable
   AsyncHttpConnection.java:82 org.eclipse.jetty.server.AsyncHttpConnection.handle
SelectChannelEndPoint.java:668 org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle
 SelectChannelEndPoint.java:52 org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run
     QueuedThreadPool.java:608 org.eclipse.jetty.util.thread.QueuedThreadPool.runJob
     QueuedThreadPool.java:543 org.eclipse.jetty.util.thread.QueuedThreadPool$3.run
               Thread.java:745 java.lang.Thread.run

**Comment by wqhhust** [comment]
the code for the resource is like the following:

    (defresource alert [id]
  :available-media-types ["application/edn"]
  :allowed-methods       [:get :put :post :options]
  :post! (fn[ctx]
           (println "in side post!.........")
           (println "********* post")
           )
  :handle-options (fn [ctx]
                    (println "********* option in alert")
                    (ring-response {:some "json from get"}
                                   {:headers {"Access-Control-Allow-Origin" "*"}})
                    )
  :handle-created (fn [ctx]
                    (println "********* get")
                    (ring-response {:some "json from get"}
                                   {:headers {"Access-Control-Allow-Origin" "*"}})
                    )
  :handle-ok             (fn [ctx]
                           (println "********* get")
                           (ring-response {:some "json from get"}
                                          {:headers {"Access-Control-Allow-Origin" "*"}})
                           ))

**Comment by ordnungswidrig** [comment]
There's a bug in how handle-options treats body responses. Working on a fix.

**Comment by wqhhust** [comment]
@ordnungswidrig 
good to know it's a bug

**Comment by ordnungswidrig** [comment]
The root cause for this is #152 because content-negotiation does not happen for options requests.

**Comment by ordnungswidrig** [comment]
Forcing the mediatype as described in https://github.com/clojure-liberator/liberator/issues/82#issuecomment-28683178 is a work around
