### ISSUE TITLE
Support for async

### ISSUE THREAD

**Issue by ansman** [clojure-liberator/liberator#91]
It would be nice if liberator would support async endpoints.

One way to do it would be to use [core.async](https://github.com/clojure/core.async). If a handler/action/decision returns a core.async channel the caller should also return a channel.

If there is interest for it I'd be happy to take a shot at an implementation.

**Comment by cch1** [comment]
After much dwell time, [ring-clojure](https://github.com/ring-clojure/ring/blob/master/CHANGELOG.md) has released version 1.6 which supports async processing.   The model that it supports is [mechanically convertible](https://www.booleanknot.com/blog/2016/07/15/asynchronous-ring.html) to aleph and http-kit.  It would seem that the ring model (an arity-three handler function) would work nicely with liberator's content negotiation and validation functionality.

**Comment by ordnungswidrig** [comment]
Core.async is independent of support of Ring's new async response processing. I think the latter would be a good feature and deserves discussion. Let's close this issue and have a separate one for Ring's async support.

**Comment by ordnungswidrig** [comment]
See #280.

**Comment by cch1** [comment]
Sounds like a good idea.  I did not realize this issue was just for core.async, but it makes sense to separate the issues as support for one does not imply support for the other.
